mbj/unparser

- lib/unparser.rb
- spec/unit/unparser_spec.rb
On my system, loading unparser in a rails app takes about 16 MiB at boot
```
unparser: 16.5391 MiB
parser/all: 15.418 MiB
parser/ruby18: 4.4492 MiB
parser/ruby19: 4.1523 MiB
parser/ruby20: 3.0742 MiB
parser/ruby22: 1.5313 MiB
parser/ruby23: 1.1055 MiB (Also required by: parser/current)
parser/ruby21: 0.5547 MiB
parser/ruby24: 0.5469 MiB
concord: 0.9219 MiB
adamantium: 0.8398 MiB
ice_nine: 0.3945 MiB
```
If we drop parser/all, we also drop 10 MiB at boot. 🎉 
```
unparser: 6.5898 MiB
parser/current: 4.625 MiB
parser/ruby23: 4.6094 MiB
concord: 0.668 MiB
adamantium: 0.6602 MiB
ice_nine: 0.4102 MiB
```
Since we only use parser current, in the tests how do we feel not loading the other parsers?
> don't require all ruby parsers when loading unparser

- Gemfile.lock
- lib/unparser/emitter/literal/primitive.rb
- spec/integrations.yml
- unparser.gemspec
I would like to update unparser to work with Ruby 2.4. I need to update devtools and mutant, since we have quite a complex dependency around here. 
I need to relax parser dependency so, I can update mutant to have relaxed dependency as well. When I will be able to install parser 2.4 I will be able to add a handler for multiple assignments AST nodes.
> Suppress Ruby 2.4 Fixnum deprecation

- spec/integrations.yml
Adds three rubyspec files (core/string/shared/to_sym.rb, language/fixtures/binary_symbol.rb and language/for_spec.rb) to the list of files excluded from the tests. Parser/unparser does not support them and they fail with at least rubies 2.3.4 - 2.5.0.
> Exclude three more rubyspec files from tests

- lib/unparser/cli.rb
The documentation for `Unparser::CLI#add_option` was slightly wrong; it listed `builder` as `Optparse::Builder`, which is a class that doesn't exist in a module that doesn't exist. This confused me as I was looking for a gem called `Optparse`.
Going back to the `add_option` method, I see it is called from `initialized` in the following block:
https://github.com/mbj/unparser/blob/7d22ef2b4482d7673b88c876d08b28c0861ebfb9/lib/unparser/cli.rb#L48-L50
Checking the class of `builder` lets conclude that it is a `OptionParser`.
```ruby
require("optparse")
OptionParser.new { |builder| puts builder.class }
"OptionParser"
```
The doc will now reflect this
> Correct documentation; add_option takes a OptionParser

- config/flay.yml
- lib/unparser/emitter/rescue.rb
- spec/unit/unparser_spec.rb
Prior to this commit, unparser would emit incorrect source representations for users using the new ruby 2.5 block syntax for rescue/ensure.
Round-tripping
```ruby
m do
foo
bar
rescue
baz
end
```
would produce
```ruby
m do
foo
bar rescue baz
end
```
instead of the original source as it should.
> Support ruby 2.5 block rescue syntax

- .circleci/config.yml
- Gemfile.lock
- unparser.gemspec
Recently, `parser` 2.6.2 came out with support for recently released Ruby 2.5.5
> Upgrade parser dependency

- Changelog.md
- lib/unparser/emitter.rb
- spec/unit/unparser_spec.rb
* This unparser specific exception type makes it easy to catch errors
originating from the specific case unparser is exposed to a node type
it does not understand.
> Change to raise unparser specific error on unknown node type

- Gemfile.lock
- lib/unparser/node_details/send.rb
- lib/unparser/node_helpers.rb
- test/corpus/literal/send.rb
- unparser.gemspec
* These need to be emitted regular and cannot be emitted in binary
syntax.
[Fix #278]
> Fix crash on binary operator selector with kwargs argument

- lib/unparser/buffer.rb
- spec/unit/unparser/buffer_spec.rb
- The last reference to this method I can find outside of the specs is in 189d9f468a7840bf8790129d8d00aa8be05a625a and appears to be unused since well before then.
- Also resolve some uncovered mutations since `Buffer#write` already returns `self`.
> Remove unused Buffer#capture_content method

- spec/unit/unparser/adamantium/memory_spec.rb
- Mainly using `unparser` as a canary for an [`rspectre`](https://github.com/dgollahon/rspectre) release.
> Remove unused `let`

- Changelog.md
- Gemfile.lock
- bin/corpus
- lib/unparser/emitter/flipflop.rb
- test/corpus/literal/flipflop.rb
- unparser.gemspec
* This requires to pin a parser release where this is fixed.
* And has to bump rubocop.
> Fix {begin,end}less {i,e}range flipflops

- .github/workflows/ci.yml
- lib/unparser/generation.rb
- spec/unit/unparser_spec.rb
I stumbled upon an error: 
```
NoMethodError: undefined method `type' for nil:NilClass
lib/unparser/node_helpers.rb:31:in `n?'
lib/unparser/node_helpers.rb:66:in `block (2 levels) in <module:NodeHelpers>'
lib/unparser/generation.rb:159:in `emit_body_member'
...
```
Which is produced while unparsing a snippet of code like this: 
```
'true ? "true" : ()'
'true ? () : "false"'
```
Unfortunately on the project I'm currently working I can't guarantee/rewrite incoming code snippets, so have to handle.
> Avoid breaking on empty begin nodes within conditionals

- lib/unparser/emitter/primitive.rb
- spec/unit/unparser_spec.rb
Original bug:
https://bugs.ruby-lang.org/issues/18905
Resolves: https://github.com/mbj/unparser/issues/359
> Add a fix for `Symbol#inspect` on `3.0`, `3.1`

- README.md
I was playing with comments-preserving unparsing and it seems like README example uses invalid API
BTW is there a reason there's no direct `Unparser.parse_with_comments` method?
> Fix README `parse_with_comments` examples

- lib/unparser/node_helpers.rb
- lib/unparser/writer/regexp.rb
- test/corpus/literal/regexp.rb
Extracted from https://github.com/mbj/unparser/pull/392
```bash
$ bundle exec bin/unparser -e '/foo #$G/'
(string)
/foo #$G/
lib/unparser/buffer.rb:149:in `write'
lib/unparser/buffer.rb:55:in `append_without_prefix'
unparser/writer/regexp.rb:69:in `write_regular'
unparser/writer/regexp.rb:59:in `emit_body'
unparser/writer/regexp.rb:45:in `each'
unparser/writer/regexp.rb:45:in `block in dispatch'
```
> Fix regexp with gvar unparsing

- lib/unparser/writer/resbody.rb
- test/corpus/semantic/rescue.rb
> Fix `resbody` with multiple indexes assignment unparsing

- lib/unparser/writer/resbody.rb
- lib/unparser/writer/rescue.rb
- test/corpus/semantic/rescue.rb
> Fix `rescue` without body unparsing

- lib/unparser/node_helpers.rb
- lib/unparser/writer/send/unary.rb
- test/corpus/literal/flipflop.rb
```bash
bundle exec bin/unparser -e 'not a...b'
(string)
not a...b
!a...b
Original-Node:
(send
(eflipflop
(send nil :a)
(send nil :b)) :!)
Generated-Node:
(erange
(send
(send nil :a) :!)
(send nil :b))
Node-Diff:
@@ -1,4 +1,4 @@
-(send
-  (eflipflop
-    (send nil :a)
-    (send nil :b)) :!)
+(erange
+  (send
+    (send nil :a) :!)
+  (send nil :b))
```
> Fix negated `flipflop` unparsing

- lib/unparser/node_helpers.rb
- lib/unparser/writer/send/unary.rb
- test/corpus/semantic/not.rb
This solution aint perfect (there are still some bugs in this area), but at least it fixes some of them.
I'll try to find some time to revisit it later.
> Fix `not` with binary operator unparsing

- lib/unparser/writer/binary.rb
- test/corpus/semantic/pattern.rb
```bash
$ bundle exec bin/unparser -e 'a in b, and c'
warning: parser/current is loading parser/ruby34, which recognizes 3.4.0-dev-compliant syntax, but you are running 3.4.3.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
(string)
a in b, and c
a in [b, ] && c
Original-Node:
(and
(match-pattern-p
(send nil :a)
(array-pattern-with-tail
(match-var :b)))
(send nil :c))
Generated-Node:
```
> Fix `match-pattern-p` with logical operator unparsing

- lib/unparser/writer/resbody.rb
- test/corpus/semantic/rescue.rb
```bash
$ bundle exec bin/unparser -e 'module A; x = 1; rescue; end'
warning: parser/current is loading parser/ruby34, which recognizes 3.4.0-dev-compliant syntax, but you are running 3.4.3.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
(string)
module A; x = 1; rescue; end
module A
x = 1 rescue
end
Original-Node:
(module
(const nil :A)
(rescue
(lvasgn :x
(int 1))
(resbody nil nil nil) nil))
Generated-Node:
```
> Fix `resbody` without body unparsing

- lib/unparser/emitter/assignment.rb
- test/corpus/literal/rescue.rb
```shell
$ bundle exec bin/unparser -e 'foo = 1, 2 rescue nil'
warning: parser/current is loading parser/ruby34, which recognizes 3.4.0-dev-compliant syntax, but you are running 3.4.3.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
(string)
foo = 1, 2 rescue nil
foo = [1, 2] rescue nil
Original-Node:
(rescue
(lvasgn :foo
(array
(int 1)
(int 2)))
(resbody nil nil
(nil)) nil)
Generated-Node:
(lvasgn :foo
(rescue
(array
(int 1)
(int 2))
(resbody nil nil
(nil)) nil))
Node-Diff:
@@ -1,7 +1,7 @@
-(rescue
-  (lvasgn :foo
+(lvasgn :foo
+  (rescue
(array
(int 1)
-      (int 2)))
-  (resbody nil nil
-    (nil)) nil)
+      (int 2))
+    (resbody nil nil
+      (nil)) nil))
Error: …
```
> Fix mass assign and `rescue` precedence during unparsing
